package context

import (
	"encoding/json"
	"time"

	"github.com/PayRam/api-orchestrator-go/internal/models"
	"github.com/google/uuid"
)

// Context represents the runtime context that flows through the orchestrator pipeline.
// This struct is NOT persisted in the database — it is purely a runtime object used
// internally by header builders, request builders, and response normalizers.
type Context struct {
	// RequestID is a unique identifier for this request execution.
	RequestID uuid.UUID `json:"request_id"`

	// Provider is the provider struct loaded from the database.
	Provider models.Provider `json:"provider"`

	// Action is the endpoint/action being called (e.g., "create_widget_url").
	Action string `json:"action"`

	// Credentials is a decrypted map of credentials (e.g., "API_KEY" → "value").
	Credentials map[string]string `json:"credentials"`

	// Input contains user input parameters (e.g., wallet address, crypto type).
	Input map[string]interface{} `json:"input"`

	// Intermediate is scratch space used by strategies and header evaluators.
	Intermediate map[string]interface{} `json:"intermediate"`

	// Headers is the final set of headers generated by the header pipeline.
	Headers map[string]string `json:"headers"`

	// Body is the final request body generated by the request builder.
	Body interface{} `json:"body"`

	// Metadata stores additional context information if needed.
	Metadata json.RawMessage `json:"metadata,omitempty"`

	// StartTime is when the context was created (for timing/metrics).
	StartTime time.Time `json:"start_time"`
}

// NewContext creates a new runtime context for pipeline execution.
func NewContext(provider models.Provider, action string, input map[string]interface{}) *Context {
	return &Context{
		RequestID:    uuid.New(),
		Provider:     provider,
		Action:       action,
		Credentials:  make(map[string]string),
		Input:        input,
		Intermediate: make(map[string]interface{}),
		Headers:      make(map[string]string),
		StartTime:    time.Now(),
	}
}

// Set adds a value to the Intermediate map (scratch space for strategies).
func (ctx *Context) Set(key string, val interface{}) {
	if ctx.Intermediate == nil {
		ctx.Intermediate = make(map[string]interface{})
	}
	ctx.Intermediate[key] = val
}

// Get retrieves a value from the Intermediate map.
// Returns nil if the key does not exist.
func (ctx *Context) Get(key string) interface{} {
	if ctx.Intermediate == nil {
		return nil
	}
	return ctx.Intermediate[key]
}

// GetOk retrieves a value from the Intermediate map with existence check.
func (ctx *Context) GetOk(key string) (interface{}, bool) {
	if ctx.Intermediate == nil {
		return nil, false
	}
	val, ok := ctx.Intermediate[key]
	return val, ok
}

// SetCredential adds a credential to the context.
func (ctx *Context) SetCredential(key, value string) {
	if ctx.Credentials == nil {
		ctx.Credentials = make(map[string]string)
	}
	ctx.Credentials[key] = value
}

// GetCredential retrieves a credential from the context.
func (ctx *Context) GetCredential(key string) (string, bool) {
	if ctx.Credentials == nil {
		return "", false
	}
	val, ok := ctx.Credentials[key]
	return val, ok
}

// SetHeader adds a header to the context.
func (ctx *Context) SetHeader(key, value string) {
	if ctx.Headers == nil {
		ctx.Headers = make(map[string]string)
	}
	ctx.Headers[key] = value
}

// GetHeader retrieves a header from the context.
func (ctx *Context) GetHeader(key string) (string, bool) {
	if ctx.Headers == nil {
		return "", false
	}
	val, ok := ctx.Headers[key]
	return val, ok
}

// MergeHeaders merges the provided headers into the context headers.
// Existing headers with the same key will be overwritten.
func (ctx *Context) MergeHeaders(h map[string]string) {
	if ctx.Headers == nil {
		ctx.Headers = make(map[string]string)
	}
	for k, v := range h {
		ctx.Headers[k] = v
	}
}

// SetBody sets the final request body.
func (ctx *Context) SetBody(b interface{}) {
	ctx.Body = b
}

// GetBody retrieves the request body.
func (ctx *Context) GetBody() interface{} {
	return ctx.Body
}

// GetInput retrieves a value from the Input map.
func (ctx *Context) GetInput(key string) (interface{}, bool) {
	if ctx.Input == nil {
		return nil, false
	}
	val, ok := ctx.Input[key]
	return val, ok
}

// GetInputString retrieves a string value from the Input map.
// Returns empty string if key doesn't exist or value is not a string.
func (ctx *Context) GetInputString(key string) string {
	if ctx.Input == nil {
		return ""
	}
	if val, ok := ctx.Input[key]; ok {
		if str, ok := val.(string); ok {
			return str
		}
	}
	return ""
}

// Duration returns the time elapsed since context creation.
func (ctx *Context) Duration() time.Duration {
	return time.Since(ctx.StartTime)
}

// OrchestratorContext is an alias for backward compatibility.
// Deprecated: Use Context instead.
type OrchestratorContext = Context
