package services

import (
	"github.com/PayRam/api-orchestrator-go/internal/models"
)

// StrategyResult represents the result of executing a strategy
type StrategyResult struct {
	// Values contains the computed values from strategy execution
	// Keys are output names, values are the computed results
	Values map[string]interface{}

	// Headers contains any headers generated by the strategy
	Headers map[string]string

	// Error contains any error that occurred during execution
	Error error
}

// StrategyExecutionContext provides the context for strategy execution
type StrategyExecutionContext struct {
	// Credentials contains decrypted credential values
	Credentials map[string]string

	// Input contains the input parameters from the request
	Input map[string]interface{}

	// Intermediate contains values computed by previous strategies
	Intermediate map[string]interface{}

	// Timestamp is the execution timestamp (for signing)
	Timestamp int64

	// Nonce is a unique value for replay protection
	Nonce string
}

// StrategyService defines the business logic interface for strategies.
// It handles CRUD operations and strategy execution for auth, signing,
// and payload generation.
type StrategyService interface {
	// CreateStrategy creates a new strategy
	CreateStrategy(strategy *models.Strategy) error

	// GetStrategyByID retrieves a strategy by ID
	GetStrategyByID(id string) (*models.Strategy, error)

	// GetStrategyByName retrieves a strategy by name
	GetStrategyByName(name string) (*models.Strategy, error)

	// ListStrategies retrieves all active strategies
	ListStrategies() ([]*models.Strategy, error)

	// GetStrategiesByType retrieves all strategies of a specific type
	GetStrategiesByType(strategyType string) ([]*models.Strategy, error)

	// UpdateStrategy updates an existing strategy
	UpdateStrategy(strategy *models.Strategy) error

	// DeleteStrategy soft deletes a strategy
	DeleteStrategy(id string) error

	// ExecuteStrategy executes a strategy by name and returns the computed values.
	// It safely evaluates the strategy logic within the provided context.
	ExecuteStrategy(strategyName string, ctx *StrategyExecutionContext) (*StrategyResult, error)

	// ExecuteStrategyByID executes a strategy by ID and returns the computed values.
	ExecuteStrategyByID(strategyID string, ctx *StrategyExecutionContext) (*StrategyResult, error)
}
